name: Build JavaScripts

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'

    - name: Install dependencies
      run: |
        npm install --save-dev @babel/core @babel/cli @babel/preset-env
        npm install --global terser

    - name: Run Babel
      run: npx babel ./static/js --out-dir ./static/js_dist --presets=@babel/preset-env

    - name: Minify javascript
      run: find ./static/js_dist -name '*.js' -exec terser {} -o {} -m -c \;

    - name: Commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "[Github Action] Build JavaScripts"
        branch: main
        push_options: "--force"
        skip_checkout: true
